name: Olympix Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug & Run Olympix Security Scanner
        uses: olympix/integrated-security@v0.1.0
        with:
          entryPoint: bash
          args: >
             -c "echo 'Running entryPoint: npx hardhat compile' &&
              npx hardhat compile --contracts ./contracts/**/*.sol --severity high --report json"
