name: Olympix Integrated Security

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Olympix Security Scanner
        uses: olympix/integrated-security@v0.1.0
        with:
          scan-type: 'full'
          fail-on: 'high'
